name: Test sample-exprss-project

on:
  workflow_run:
    workflows:
      - "Lint sample-exprss-project"
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: sample-exprss-project

      - name: Execute Unit Test
        run: npm run test
        working-directory: sample-exprss-project

      - name: Execute E2E Test
        run: npm run test:e2e
        working-directory: sample-exprss-project
